image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .nuget/packages/
    - .dotnet/

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet test --no-build --verbosity normal --configuration Release
